[package]
name = "edr_packs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib","lib"]
name = "edr_packs"

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.32.1", features = ["token_2022","associated_token"] }
