[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
edr_packs = "H7bsCvtWx5TRF9MztdL9AKkZzhbwdDUQtotjUQPwVCbi"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "keys/seller.json"

[workspace]
members = ["programs/edr_packs"]
